# -*- coding: utf-8 -*-
print ("Hola, ingresa tu nombre:")
nombre = input()
print (nombre + " adivinare tu edad.")
input("Presiona una tecla para continuar.")
print (nombre + " ingresa el año de nacimiento:")
nacimiento= input()
input("Presiona una tecla para continuar.")
print (nombre + " ingresa el año actual:")
actual= input()
edad= int(actual)-int(nacimiento)
input("Presiona una tecla para contunuar.")
print (nombre + "tu edad es:")
print (edad)
