# -*- coding: utf-8 -*-
lista = []
num = int(input("Ingresa un número: "))
lista.append (num)
print ("Presiona una tecla para continuar.")
num = int(input("Ingresa un número: "))
lista.append (num)
print ("Presiona una tecla para continuar.")
num = int(input("Ingresa un número: "))
lista.append (num)
print ("Presiona una tecla para continuar.")
num = int(input("Ingresa un número: "))
lista.append (num)
print ("Presiona una tecla para continuar.")
num = int(input("Ingresa un número: "))
lista.append (num)
print ("Presiona una tecla para continuar.")
suma = sum(lista)
menor = min(lista)
mayor = max(lista)
print ("Los números de la lista son: ", sorted(lista))
print ("La suma de los números de la lista es: ", suma)
print ("El número menor de la lista es: ", menor)
print ("El número mayor de la lista es: ", mayor)
